### PR TITLE
Featured numbers

### PR DESCRIPTION
**Pull request by attiks**

### CODE REVIEW

**Review by rupl — COMMENTED** [review]
When selecting RW figures, it works well.

All the other categories eventually tell me "An illegal choice has been detected" and you can't save until you find a valid configuration (losing any valid stuff I'd managed to load into Layout Builder beforehand). I took a couple videos if you want them, but it seems pretty likely that you reproduce this if using any source besides RW.

I did tail my logs while doing this and there were no 500s (which has been my mistake before because my local isn't configured correctly). Everything seems to return and the fields even fill in with appropriate options, but then Drupal gets cranky about the combo of options chosen.

**Comment by rupl** [comment]
For FTS if I go and choose things I know exist (e.g. Ukraine has a long, storied history in FTS) then I am able to backpedal out of the error and at least save some content. But for CBFP and CERF it seemed to be a one way hole. Even switching sources wouldn't get rid of the error. I'm not certain, but I feel like the primary modal which holds the title/text/numbers fields somehow gets notified of the error and halts use of the secondary modal which holds the Featured Number editor config widgets.

**Comment by attiks** [comment]
Strange

image

and 

image

Does it work if you add a regular paragraph for CERF?

image

**Comment by rupl** [comment]
Yes, adding a "Figures - CERF" paragraph worked in all cases. I configured perhaps 4 or 5 of them to test.

Maybe we can just chalk this up to me not having my local properly configured? ¯\\\_(ツ)\_/¯

**Review by rupl — APPROVED** [review]
You know what must have happened? One of my three internet outages probably interfered with my testing yesterday. Let's assume that and try it on dev ;)

**Pull request merged**
