### PR TITLE
chore: use config split

### PR DESCRIPTION
**Pull request by attiks**
First attempt broker dev deploy

### CODE REVIEW

**Comment by rupl** [comment]
Do you have an idea of how to setup this branch if I started from `develop`? I'm getting circular errors about `config_split` and `config_filter` being either not enabled, or being enabled and unable to uninstall because of it.

**Comment by lazysoundsystem** [comment]
@rupl thanks for testing - I was also having trouble getting that to work (or at least the tests to pass) - can you try with https://github.com/UN-OCHA/numbers-site/pull/84 . Try with `composer install` first and, if that works for you, we can merge that and close this.

**Comment by attiks** [comment]
> Do you have an idea of how to setup this branch if I started from `develop`? I'm getting circular errors about `config_split` and `config_filter` being either not enabled, or being enabled and unable to uninstall because of it.

Uninstall config_filter and config_split first and add `$config['config_split.config_split.config_dev']['status'] = TRUE;` to your `settings/php`

**Comment by attiks** [comment]
Closing in favor of #84

**Pull request closed without merging**
