### PR TITLE
chore: Drupal 10 runs on PHP 8.2.

### PR DESCRIPTION
**Pull request by cafuego**
And since we do not need to run sass, the builder image is not needed either.

Refs: OPS-9461

### CODE REVIEW

**Comment by attiks** [comment]
> Error response from daemon: manifest for public.ecr.aws/unocha/numbers-site:local not found: manifest unknown: Requested image not found

**Comment by cafuego** [comment]
You forgot to add the PHP 8.2 patch file :-)

**Comment by attiks** [comment]
> Failed. The supported PHP versions are 7.2-8.1.
Failed. Elastic PHP agent extension is not supported for the existing PHP installation.
ERROR: apm-agent-php-1.6.1.post-install: script exited with error 1
1 error; 370 MiB in 205 packages

**Comment by cafuego** [comment]
Aight, I can update that tomorrow. On 19 Jul 2023, at 21:24, Peter Droogmans ***@***.***> wrote:﻿

Failed. The supported PHP versions are 7.2-8.1.
Failed. Elastic PHP agent extension is not supported for the existing PHP installation.
ERROR: apm-agent-php-1.6.1.post-install: script exited with error 1
1 error; 370 MiB in 205 packages

**Pull request merged**
