### PR TITLE
chore: 21-02-2023 prep release

### PR DESCRIPTION
**Pull request by rupl**

### CODE REVIEW

**Comment by rupl** [comment]
It sounds like the error I read came form a linter, but it did not instruct me to use that flag, so when I ran `composer update` which were the exact instructions, it still failed:

> The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update` or `composer update <package name>`.

I'll keep it in mind for next time, thanks!

**Comment by rupl** [comment]
@emmajane this is ready for a yolo

**Comment by cafuego** [comment]
Composer is open source, time for a PR ;-)- Peter.On 23 Feb 2023, at 18:41, Chris Ruppel ***@***.***> wrote:﻿
It sounds like the error I read came form a linter, but it did not instruct me to use that flag, so when I ran composer update which were the exact instructions, it still failed:

The lock file is not up to date with the latest changes in composer.json, it is recommended that you run composer update or composer update <package name>.

I'll keep it in mind for next time, thanks!

**Review by attiks — APPROVED** [review]

**Comment by attiks** [comment]
https://github.com/UN-OCHA/ocha-api-site/pull/35 needs to be deployed first

**Pull request merged**
